name: scasc
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
     - -e ../pyviewer
     - -r requirements.txt

# conda env create --force -f environment.yml
